# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/profile/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('file_type',)},
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
