# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180829_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
