# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-02 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_register_confirm_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('audio_file',)},
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=2, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='static/upload/audio'),
            preserve_default=False,
        ),
    ]
