# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20180902_0545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('song_title',)},
        ),
        migrations.AddField(
            model_name='album',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
