# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20180905_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='create_date',
            field=models.DateField(),
        ),
    ]
