# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20180907_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='birth_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='first_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='last_name',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
