# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20180907_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='birth_date',
        ),
    ]
