# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_album_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='create_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
