# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-08 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_album_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='create_date',
        ),
    ]
